# Diccionario de aliases para componentes comunes
COMPONENT_ALIASES = {
    # SERIE ROJA
    "HEMOGLOBINA": [
        "HB", "HGB", "HEMOG", "HEMOGLOBINA TOTAL", "HB TOTAL",
        "HEMOGLOBINA SANGRE TOTAL", "HGB TOTAL"
    ],
    
    "HEMATOCRITO": [
        "HTO", "HCT", "HCTO", "VOLUMEN GLOBULAR",
        "VOLUMEN ERITROCITARIO", "PACKED CELL VOLUME", "PCV"
    ],
    
    "ERITROCITOS": [
        "RBC", "GLOBULOS ROJOS", "GR", "ERITROS", "HEMATIES",
        "RECUENTO ERITROCITARIO", "RECUENTO DE GLOBULOS ROJOS",
        "CONTEO DE ERITROCITOS", "RED BLOOD CELLS"
    ],
    
    "VCM": [
        "VOLUMEN CORPUSCULAR MEDIO", "VOL. CORP. MEDIO", "VOLUMEN MEDIO",
        "MCV", "MEAN CORPUSCULAR VOLUME", "VMCR"
    ],
    
    "HCM": [
        "HEMOGLOBINA CORPUSCULAR MEDIA", "HB CORPUSCULAR MEDIA",
        "MCH", "MEAN CORPUSCULAR HEMOGLOBIN", "HBCM"
    ],
    
    "CHCM": [
        "CONCENTRACION HB CORPUSCULAR MEDIA", "CONCENTRACION MEDIA HB",
        "MCHC", "MEAN CELL HEMOGLOBIN CONCENTRATION",
        "CONCENTRACION MEDIA HEMOGLOBINA", "CHGM"
    ],
    
    "RDW": [
        "ANCHO DISTRIBUCION ERITROCITARIA", "RED CELL DISTRIBUTION WIDTH",
        "INDICE DISTRIBUCION ERITROCITOS", "AMPLITUD ERITROCITARIA",
        "RDW-CV", "RDW-SD", "IDH"
    ],
    
    "RETICULOCITOS": [
        "RETIC", "RET", "RETICULOCITOS PORCENTAJE", "RETIC %",
        "CONTEO RETICULOCITOS", "RECUENTO RETICULOCITOS",
        "RETICULOCITOS ABSOLUTOS", "RETIC#"
    ],

    # SERIE BLANCA
    "LEUCOCITOS": [
        "WBC", "GLOBULOS BLANCOS", "GB", "LEUCOS", "LEUC",
        "WHITE BLOOD CELLS", "LEUCOCITOS TOTALES",
        "CONTEO DE LEUCOCITOS", "RECUENTO LEUCOCITARIO"
    ],
    
    "NEUTROFILOS": [
        "NEU", "NEUT", "PMN", "NEUTROFILOS SEGMENTADOS",
        "NEUTROFILOS TOTALES", "GRANULOCITOS NEUTROFILOS",
        "NEUTROFILOS ABSOLUTOS", "NEUTROFILOS %"
    ],
    
    "LINFOCITOS": [
        "LINF", "LYM", "LINFOS", "LINFOCITOS TOTALES",
        "LINFOCITOS ABSOLUTOS", "LYM#", "LINFOCITOS %",
        "LYMPHOCYTES", "LIN"
    ],
    
    "MONOCITOS": [
        "MON", "MONO", "MONOCITOS TOTALES", "MONOCITOS ABSOLUTOS",
        "MON#", "MONOCITOS %", "MONOCYTES", "MC"
    ],
    
    "EOSINOFILOS": [
        "EOS", "EOSI", "EOSINOFILOS TOTALES", "EOSINOFILOS ABSOLUTOS",
        "EOS#", "EOSINOFILOS %", "EOSINOPHILS", "EO"
    ],
    
    "BASOFILOS": [
        "BAS", "BASOF", "BASOFILOS TOTALES", "BASOFILOS ABSOLUTOS",
        "BAS#", "BASOFILOS %", "BASOPHILS", "BA"
    ],

    # PLAQUETAS
    "PLAQUETAS": [
        "PLT", "TROMBOCITOS", "PLAQ", "PLAQUETAS TOTALES",
        "PLATELETS", "RECUENTO PLAQUETARIO", "PLT#",
        "THROMBOCYTES", "CONTEO DE PLAQUETAS"
    ],
    
    "VPM": [
        "VOLUMEN PLAQUETARIO MEDIO", "MPV", "MEAN PLATELET VOLUME",
        "VOL MEDIO PLAQUETARIO", "VOLUMEN MEDIO PLAQUETARIO"
    ],

    # OTROS INDICES
    "RAN": [
        "RECUENTO ABSOLUTO NEUTROFILOS", "NEUTROFILOS ABSOLUTOS",
        "ANC", "ABSOLUTE NEUTROPHIL COUNT", "CAN"
    ],
    # METABOLITOS Y SUSTRATOS
    "GLICEMIA": [
        "GLUCOSA", "GLUCEMIA", "GLUC", "GLU", "AZUCAR EN SANGRE",
        "GLICEMIA BASAL", "GLUCOSA BASAL", "GLUCOSA SERICA",
        "GLUCOSE", "DEXTROSA", "GLY", "FBS", "GLUCOSA AYUNAS"
    ],
    
    "UREA": [
        "BUN", "NITROGENO UREICO", "AZOE", "BLOOD UREA NITROGEN",
        "UREA SERICA", "UREA NITROGEN", "UREA PLASMATICA",
        "N UREICO", "NU", "UREA EN SANGRE"
    ],
    
    "CREATININA": [
        "CREA", "CR", "CREAT", "CREATININA SERICA",
        "CREATININE", "CREATININA PLASMATICA", "CREA SERICA"
    ],
    
    "ACIDO_URICO": [
        "AU", "URICO", "ACIDO URICO SERICO", "URIC ACID",
        "UA", "URATO", "ACIDO URICO PLASMATICO",
        "URICEMIA", "AC URICO"
    ],

    # PROTEINAS
    "PROTEINAS_TOTALES": [
        "PROT TOT", "PROTEINAS TOT", "PT", "TOTAL PROTEIN",
        "PROTEINAS", "PROTEIN TOTAL", "PROT TOTALES",
        "PROTEINAS SERICAS TOTALES"
    ],
    
    "ALBUMINA": [
        "ALB", "ALBUMINA SERICA", "ALBUMIN", "SEROALBUMINA",
        "ALB SERICA", "ALBUMINA PLASMATICA", "SERUM ALBUMIN"
    ],
    
    "GLOBULINA": [
        "GLOB", "GLOBULINAS", "GLOBULINAS TOTALES", "GLOBULINS",
        "GLOB TOT", "GLOBULINAS SERICAS", "GLOB TOTAL"
    ],

    # ELECTROLITOS
    "SODIO": [
        "NA", "NA+", "SODIO SERICO", "NATREMIA", "SODIUM",
        "SODIO PLASMATICO", "ELECTROLITO SODIO"
    ],
    
    "POTASIO": [
        "K", "K+", "POTASIO SERICO", "KALEMIA", "POTASSIUM",
        "POTASIO PLASMATICO", "ELECTROLITO POTASIO"
    ],
    
    "CLORO": [
        "CL", "CL-", "CLORO SERICO", "CLOREMIA", "CHLORIDE",
        "CLORO PLASMATICO", "ELECTROLITO CLORO"
    ],
    
    "CALCIO": [
        "CA", "CA++", "CALCIO SERICO", "CALCEMIA", "CALCIUM",
        "CALCIO TOTAL", "CALCIO IONICO", "CA TOTAL",
        "CA IONIZADO", "CALCIO PLASMATICO"
    ],
    
    "FOSFORO": [
        "P", "FOSFORO SERICO", "FOSFOREMIA", "PHOSPHORUS",
        "FOSFATO", "P INORGANICO", "FOSFORO INORGANICO",
        "FOSFORO PLASMATICO"
    ],
    
    "MAGNESIO": [
        "MG", "MG++", "MAGNESIO SERICO", "MAGNESEMIA",
        "MAGNESIUM", "MAGNESIO PLASMATICO", "MG TOTAL"
    ],

    # ENZIMAS HEPATICAS
    "GOT_AST": [
        "AST", "TGO", "TRANSAMINASA GOT", "GOT/AST",
        "ASPARTATO AMINOTRANSFERASA", "SGOT",
        "ASPARTATE AMINOTRANSFERASE", "GOT", "AST/TGO"
    ],
    
    "GPT_ALT": [
        "ALT", "TGP", "TRANSAMINASA GPT", "GPT/ALT",
        "ALANINA AMINOTRANSFERASA", "SGPT",
        "ALANINE AMINOTRANSFERASE", "GPT", "ALT/TGP"
    ],
    
    "GGT": [
        "GAMMA GT", "GAMMA GLUTAMIL TRANSFERASA",
        "GAMMA GLUTAMILTRANSFERASA", "γ-GT", "GGTP",
        "GAMMA GLUTAMYL TRANSFERASE", "G-GT"
    ],
    
    "FOSFATASA_ALCALINA": [
        "FA", "FAL", "ALP", "ALKP", "FOSFATASA ALC",
        "ALKALINE PHOSPHATASE", "FOSFATASAS ALCALINAS",
        "FOSFATASA ALCALINA TOTAL"
    ],

    # BILIRRUBINAS
    "BILIRRUBINA_TOTAL": [
        "BT", "BILIRR TOTAL", "BILIRRUBINA TOT",
        "TOTAL BILIRUBIN", "BILIRRUBINA SERICA TOTAL",
        "TBIL", "BILIRRUBINAS TOTALES"
    ],
    
    "BILIRRUBINA_DIRECTA": [
        "BD", "BILIRR DIRECTA", "BILIRRUBINA DIR",
        "DIRECT BILIRUBIN", "BILIRRUBINA CONJUGADA",
        "DBIL", "BILIRRUBINA DIRECTA SERICA"
    ],
    
    "BILIRRUBINA_INDIRECTA": [
        "BI", "BILIRR INDIRECTA", "BILIRRUBINA IND",
        "INDIRECT BILIRUBIN", "BILIRRUBINA NO CONJUGADA",
        "IBIL", "BILIRRUBINA INDIRECTA SERICA"
    ],

    # PERFIL LIPÍDICO
    "COLESTEROL_TOTAL": [
    "COL TOTAL", "COL-T", "COLEST TOTAL", "COLESTEROL",
    "CT", "TOTAL CHOLESTEROL", "COLESTEROL SERICO",
    "COLESTEROL TOTAL SERICO", "CHOLESTEROL", "COL T",
    "COLESTEROL TOTAL"
    ],
    
    "COLESTEROL_HDL": [
        "HDL", "COL HDL", "COL-HDL", "HDL-COLESTEROL", "HDL-C",
        "COLESTEROL HDL", "HDL COLESTEROL", "C-HDL", "COL. HDL",
        "HIGH DENSITY LIPOPROTEIN", "LIPOPROTEINA DE ALTA DENSIDAD",
        "HDL DIRECTO", "HDL-COLESTEROL DIRECTO", "COLESTEROL-HDL"
    ],

    "COLESTEROL_LDL": [
        "LDL", "COL LDL", "COL-LDL", "LDL-COLESTEROL", "LDL-C",
        "COLESTEROL LDL", "LDL COLESTEROL", "C-LDL", "COL. LDL",
        "LOW DENSITY LIPOPROTEIN", "LIPOPROTEINA DE BAJA DENSIDAD",
        "LDL CALCULADO", "LDL FRIEDEWALD", "COLESTEROL-LDL"
    ],

    "TRIGLICERIDOS": [
        "TG", "TRIGLIC", "TRIGLICERIDOS TOTALES", "TRIGLICÉRIDOS",
        "TRIGLYCERIDES", "TAG", "TRIGLICERIDOS SERICOS",
        "TRIACILGLICEROLES", "TRIACILGLICERIDOS",
        "TRIGLICERIDOS TOT", "TRIGLICERIDOS T",
        "TRIGLICERIDOS TOTAL", "TG TOTAL"
    ],

    "INDICE_ATEROGENICO": [
        "INDICE (COL. TOTAL/HDL)", "COL-T/HDL", "INDICE ATEROGENICO",
        "INDICE DE RIESGO", "RELACION COL/HDL", "INDICE DE CASTELLI",
        "COCIENTE ATEROGENICO", "INDICE ATEROGENICO DE CASTELLI",
        "RELACION LDL/HDL", "INDICE DE RIESGO CORONARIO",
        "COL/HDL", "LDL/HDL", "INDICE COL/HDL"
    ],

    # ENZIMAS CARDÍACAS
    "CPK_TOTAL": [
        "CPK", "CK", "CREATINA QUINASA", "CREATINE KINASE",
        "CK TOTAL", "CPK TOTAL", "CREATINA FOSFOQUINASA",
        "CREATINFOSFOQUINASA", "CK-TOTAL"
    ],
    
    "CPK_MB": [
        "CK-MB", "CPK-MB", "CREATINA QUINASA MB",
        "CREATINE KINASE-MB", "CK MB", "CPK MB ACTIVIDAD",
        "CK-MB MASA", "CKMB"
    ],
    
    "TROPONINA_I": [
        "TNI", "TROP I", "TROPONINA I CARDIACA",
        "CARDIAC TROPONIN I", "cTnI", "TROPONINA I ULTRASENSIBLE",
        "HS TROPONINA I"
    ],
    
    "TROPONINA_T": [
        "TNT", "TROP T", "TROPONINA T CARDIACA",
        "CARDIAC TROPONIN T", "cTnT", "TROPONINA T ULTRASENSIBLE",
        "HS TROPONINA T"
    ],

    # HORMONAS TIROIDEAS
    "TSH": [
        "HORMONA ESTIMULANTE TIROIDEA", "TIROTROPINA",
        "THYROID STIMULATING HORMONE", "TSH ULTRASENSIBLE",
        "THYROTROPIN", "TSH BASAL", "TSH 3G"
    ],
    
    "T4_TOTAL": [
        "T4", "TIROXINA TOTAL", "THYROXINE",
        "T4 TOTAL", "TETRAYODOTIRONINA TOTAL",
        "TOTAL T4", "TIROXINA"
    ],
    
    "T4_LIBRE": [
        "FT4", "T4L", "FREE T4", "TIROXINA LIBRE",
        "T4 FREE", "T4 LIBRE", "TETRAYODOTIRONINA LIBRE",
        "FREE THYROXINE"
    ],
    
    "T3_TOTAL": [
        "T3", "TRIYODOTIRONINA TOTAL", "TRIIODOTHYRONINE",
        "T3 TOTAL", "TOTAL T3", "TRIYODOTIRONINA",
        "T3 SERICA"
    ],
    
    "T3_LIBRE": [
        "FT3", "T3L", "FREE T3", "TRIYODOTIRONINA LIBRE",
        "T3 FREE", "T3 LIBRE", "FREE TRIIODOTHYRONINE",
        "T3 LIBRE SERICA"
    ],
    # MARCADORES TUMORALES
    "AFP": [
        "ALFA FETOPROTEINA", "ALPHA FETOPROTEIN",
        "ALFAFETOPROTEINA", "α-FETOPROTEINA",
        "ALPHA-1-FETOPROTEIN", "AFP SERICA"
    ],
    
    "CEA": [
        "ANTIGENO CARCINOEMBRIONARIO", "CARCINOEMBRYONIC ANTIGEN",
        "AG CARCINOEMBRIONARIO", "CEA TOTAL",
        "ANTÍGENO CARCINOEMBRIONARIO SÉRICO"
    ],
    
    "CA_125": [
        "CANCER ANTIGEN 125", "CA125", "CA-125",
        "ANTIGENO CARBOHIDRATO 125", "AG CA 125",
        "MARCADOR CA 125", "CA 125 II"
    ],
    
    "PSA_TOTAL": [
        "PSA", "ANTIGENO PROSTATICO ESPECIFICO",
        "PROSTATE SPECIFIC ANTIGEN", "PSA TOTAL",
        "AG PROSTÁTICO", "ANTÍGENO PROSTÁTICO"
    ],
    
    "PSA_LIBRE": [
        "FPSA", "PSA FREE", "PSA LIBRE",
        "FREE PSA", "PSA-L", "PSA LIBRE TOTAL"
    ],

    # COAGULACIÓN
    "TIEMPO_PROTROMBINA": [
        "TP", "PT", "PROTROMBINA", "PROTHROMBIN TIME",
        "TIEMPO DE QUICK", "QUICK", "TIEMPO DE PROTROMBINA",
        "T PROTROMBINA"
    ],
    
    "INR": [
        "INTERNATIONAL NORMALIZED RATIO",
        "RAZÓN NORMALIZADA INTERNACIONAL",
        "ÍNDICE INTERNACIONAL NORMALIZADO",
        "RELACION NORMALIZADA INTERNACIONAL"
    ],
    
    "TTPA": [
        "TIEMPO PARCIAL DE TROMBOPLASTINA ACTIVADA",
        "PTT", "APTT", "TIEMPO DE TROMBOPLASTINA",
        "ACTIVATED PARTIAL THROMBOPLASTIN TIME",
        "TIEMPO DE CEFALINA", "TPT ACTIVADO"
    ],
    
    "FIBRINOGENO": [
        "FIB", "FACTOR I", "FIBRINOGENO DERIVADO",
        "FIBRINOGENO FUNCIONAL", "FIBRINOGEN",
        "FACTOR 1", "FIBRINOGENO COAGULABLE"
    ],

    # MARCADORES INFLAMATORIOS
    "PCR": [
        "PROTEINA C REACTIVA", "C REACTIVE PROTEIN",
        "PCR ULTRASENSIBLE", "HS-PCR", "PCR-US",
        "PROTEINA C REACTIVA ULTRASENSIBLE",
        "CRP", "PCR CUANTITATIVA"
    ],
    
    "VSG": [
        "VES", "ESR", "ERITROSEDIMENTACION",
        "VELOCIDAD ERITROSEDIMENTACION",
        "VELOCIDAD DE SEDIMENTACION GLOBULAR",
        "SEDIMENTACION", "ERITROSEDIMENTACION GLOBULAR"
    ],

    # INMUNOLOGÍA Y SEROLOGÍA
    "FACTOR_REUMATOIDEO": [
        "FR", "RF", "LATEX", "FACTOR REUMATICO",
        "RHEUMATOID FACTOR", "FR CUANTITATIVO",
        "FACTOR REUMATOIDEO LATEX"
    ],
    
    "ASTO": [
        "ANTI-ESTREPTOLISINA O", "ANTIESTREPTOLISINA",
        "ASO", "ANTI STREPTOLYSIN O",
        "ESTREPTOLISINA O", "AELO"
    ],

    # VITAMINAS
    "VITAMINA_B12": [
        "B12", "CIANOCOBALAMINA", "COBALAMINA",
        "VIT B12", "VITAMIN B12", "B12 SERICA",
        "COBALAMIN"
    ],
    
    "VITAMINA_D": [
        "25-OH-D", "25 HIDROXI VITAMINA D",
        "25-HYDROXYVITAMIN D", "VIT D TOTAL",
        "25-OH-VITAMINA D", "CALCIDIOL",
        "25-OH-VIT D"
    ],
    
    "ACIDO_FOLICO": [
        "FOLATO", "FOLATOS", "FOLIC ACID",
        "VITAMINA B9", "FOL", "FOLICO",
        "ACIDO FOLICO SERICO"
    ],

    # MARCADORES HEPÁTICOS ADICIONALES
    "LDH": [
        "DESHIDROGENASA LACTICA", "DHL",
        "LACTATO DESHIDROGENASA", "LACTATE DEHYDROGENASE",
        "LD", "LÁCTICO DESHIDROGENASA"
    ],
    
    # MARCADORES DE FUNCIÓN RENAL
    "MICROALBUMINURIA": [
        "MAU", "MICRO ALB", "ALBUMINA EN ORINA",
        "MICROALB", "ALBUMINA URINARIA",
        "MICROALBUMINA", "ALB URINARIA"
    ],
    
    "CLEARENCE_CREATININA": [
        "DEPURACION DE CREATININA", "ACLARAMIENTO DE CREATININA",
        "CLEARANCE CREATININA", "CCR", "DEPURACION CREATININA",
        "CLEAREANCE DE CREATININA"
    ]
}